In this script we have done the following:

1. We have added a 'try...except' to do_calc.
2. We have added logging to log exceptions.

It now can finish more gracefully, and log exceptions in
the task, and handle them as we wish.

So when tasks are awaited, we get the expected result.

But here one problem with our example:

1. When we do a CTRL-C, we get a KeyboardInterrupt exception.

Let's handle that with signals in the next example.
